### ISSUE TITLE
[Question] minimize memorization in ACKTR?

### ISSUE THREAD

**Issue by jarlva** [hill-a/stable-baselines#1016]
Hello, I'm using ACKTR to solve a gym classic-like problem that takes over an hour to solve. I noticed in playback that it repeats the same actions in the same places. As if it memorized the solution. Is there a way to minimize memorization?

I understand that adding parameter noise can improve results. Can it also minimize memorization? 
I was thinking of adding slight randomness to the input data but wanted to know if there is a better way in SB (hopefully I'm not mixing two separate issues)?

p.s. I don't see in the readme site a noise parameter for ACKTR

**Comment by Miffyli** [comment]
This goes more onto "general RL" side, rather than stable-baselines specific. Such "memorization" is expected if the environment is deterministic and does not change between runs notably, as with those actions the agent will reach high reward. Of course, if it always does same actions it will never try something new (i.e. explore) and potentially is stuck at sub-optimal performance. Parameter noise helps here by slightly modifying the actions and trying different things. Randomizing observations could potentially help as well (search for "domain randomization").

If you have no further questions/issues related to stable-baselines, you may close this issue.

**Comment by jarlva** [comment]
Thanks @Miffyli
