### ISSUE TITLE
Value estimation update?

### ISSUE THREAD

**Issue by E666GT** [hill-a/stable-baselines#1061]
Hi SB Team,

Thanks for your great work in SB. May I know, is there an easy way to change the value estimation update strategy?

for example, I believe in the PPO2, 
**(TD update) :  v(t) = decay*v(t+1) + r(t).** 

I may need it 

**v(t)=r(t)+r(t+1)+...+r(t_end)?**

Thanks for your reply!

**Comment by araffin** [comment]
>Thanks for your great work in SB. May I know, is there an easy way to change the value estimation update strategy?

It depends on the algorithm.
I would recommend you to take a look at [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) (SB3) which is easier to hack ;)
You would need to change the `RolloutBuffer` (take a look at where advantages are computed) and the `train()` method to use Monte-Carlo (MC) estimates as target for the value function (instead of the current GAE).

> (TD update) : v(t) = decay*v(t+1) + r(t).

this is not what is implemented currently (please take a look at the GAE paper and at SB3 code ;).

>I may need it

I would be careful changing those kind of important details...

**Comment by E666GT** [comment]
> > Thanks for your great work in SB. May I know, is there an easy way to change the value estimation update strategy?
> 
> It depends on the algorithm.
> I would recommend you to take a look at [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) (SB3) which is easier to hack ;)
> You would need to change the `RolloutBuffer` (take a look at where advantages are computed) and the `train()` method to use Monte-Carlo (MC) estimates as target for the value function (instead of the current GAE).
> 
> > (TD update) : v(t) = decay*v(t+1) + r(t).
> 
> this is not what is implemented currently (please take a look at the GAE paper and at SB3 code ;).
> 
> > I may need it
> 
> I would be careful changing those kind of important details...

Thanks for your quick reply, i will have a look of your implementation.
