### ISSUE TITLE
Is there a way to know the model architecture ?

### ISSUE THREAD

**Issue by xunpla123** [hill-a/stable-baselines#1068]
Hi I've trained a SAC+HER model and it performed well on the task. But i want to know the details about the model. 

How should I do to get the detail table like model.summary() function used in keras model ?

**Comment by araffin** [comment]
>How should I do to get the detail table like model.summary() function used in keras model ?

Hello,
there are two ways:
- one is to specify explicity the network architecture (see doc, `policy_kwargs` argument)
- second is to look at the source code, for SAC, default network is a two-layers network (fully connected) of 64 units each, but as mentioned in the documentation, we recommended taking a look at the [rl-zoo](https://github.com/DLR-RM/rl-baselines3-zoo) (here the Stable-Baselines3 version, more up to date) for tuned values (on other SAC+HER tasks)

**Comment by xunpla123** [comment]
Thanks for your reply. 

I know `policy_kwargs` can specify explicity the layer size and units or change them. If I can get more detailed information like total params or trainable params ?

like this : 

![table](https://user-images.githubusercontent.com/56833852/104714335-0f4b4480-5760-11eb-91c6-8620efd2bdbf.png)

I saved the model to a compressed file and there are files called parameters and parameter_list. Is there any way to get more details from them ?

**Comment by araffin** [comment]
>I saved the model to a compressed file and there are files called parameters and parameter_list. Is there any way to get more details from them ?

Please read the documentation for that ;)
but yes, you can get the number of parameters for them (and usually all parameters are trainable)

**Comment by olyanos** [comment]
Hi,
I also had this question and I tried:
`model.policy
`or 
`print(model.policy)
`and it works.
output:
ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential()
    (policy_net): Sequential(
      (0): Linear(in_features=50, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=50, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
      (4): Linear(in_features=64, out_features=64, bias=True)
      (5): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=50, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)

**Comment by EoinKenny** [comment]
This actually doesn't work for me when I try print the model.

Is there now way to view the model and edit the layers etc after training? I really need to "get into" the model and switch around parameters etc. after it trains. Can I just get a Pytorch object instantiation of the model as if I just trained it in pytorch in the first place? Thanks!

**Comment by olyanos** [comment]
Hi Kenny,
I am not sure if I understand your question completely nor I am as qualified to answer questions like the people who actually developed the library. However, I will try to answer to the best of my knowledge.
In terms of editing the layers after training, I am not sure if you are trying to do so because you want to use transfer learning and re-train the model with a new output layer and preserve the knowledge of the previous model. 
In order to do so, I think you would need to first save the model in desk then reload it and remove the last layer.

In terms of editing the DNNs of the model you have you can use:
`
# Edit the model design
policy_kwargs = dict(net_arch=[dict(pi=[128,128], vf=[128,128])])
`

In terms of printing the model details, I just tried it and it produces the following:
```
==========================================================
Model Design:
ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential()
    (policy_net): Sequential(
      (0): Linear(in_features=900, out_features=128, bias=True)
      (1): Tanh()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=900, out_features=128, bias=True)
      (1): Tanh()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=128, out_features=900, bias=True)
  (value_net): Linear(in_features=128, out_features=1, bias=True)
)
==========================================================

```
versions of my libraries:
Tensorflow version = 2.8.0
Keras version = 2.8.0
Stable baseline version = 1.2.0
OpenAI Gym version = 0.19.0
Torch version = 1.11.0
Python version = 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
