### ISSUE TITLE
[Question] GAIL : ValueError: Shape must be rank 3 but is rank 2 for 'adversary/concat' .....

### ISSUE THREAD

**Issue by romain-mondelice** [hill-a/stable-baselines#1075]
Hello everyone,
I can perfectly train with my CustomEnv the DQN and TRPO models as planed.
But when I'm trying to use GAIL model I got this error :
```python
ValueError: Shape must be rank 3 but is rank 2 for 'adversary/concat' (op: 'ConcatV2') with input shapes: [?,64,27], [?,3], [].
```

Here is the action_space and the observation_space of my CustomEnv :
```python
self.action_space = spaces.Discrete(3)
self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape = (states.shape[1],states.shape[2]))
```
So the final shape of a state and an action is respectivly (64, 27) and ()
```python
In [51]: train_env.state.shape
Out[51]: (64, 27)
```
```python
In [52]: train_env.action.shape
Out[52]: ()
```

**The example of the doc for the GAIL model works perfectly fine [GAIL doc](https://stable-baselines.readthedocs.io/en/master/modules/gail.html).**
Moreover the check_env don't return any warnings.

I'm still a novice and this may be a silly question. Maybe I just can't use GAIL with the dim of my states / actions.
I need your expertise.

**System Info**
 * Python version : 3.6
 * Tensorflow version : 1.8 (I have try to change the version to 1.14 and 1.15 but I got the same error)

Thank you in advance,
Best and kinds regards

**Comment by araffin** [comment]
Hello,

Probably a duplicate of https://github.com/hill-a/stable-baselines/issues/1070 and https://github.com/hill-a/stable-baselines/issues/1074 : reshape your obs space to be 1D and it should work ;)

Yes, that check is missing in the env checker, probably because it works with everything but GAIL...

Anyway, I would recommend you to use the better maintained GAIL implementation of the imitation lib: https://github.com/HumanCompatibleAI/imitation
(now based on Stable-Baselines3)

**Comment by romain-mondelice** [comment]
Both solutions work, thank you very much!

**Comment by hougiebear** [comment]
Just leaving a comment here for others in future to easily to flatten their observations.
You can use the openai gym ObservationWrapper
```
import gym.spaces as spaces
from gym import ObservationWrapper


from gym.spaces import Box
class FlattenObservation(ObservationWrapper):
    r"""Observation wrapper that flattens the observation."""
    def __init__(self, env):
        super(FlattenObservation, self).__init__(env)
        self.observation_space = spaces.flatten_space(env.observation_space)

    def observation(self, observation):
        return spaces.flatten(self.env.observation_space, observation)

env = gym.make('CustomEnvName-v0')
env = FlattenObservation(env)
```
I've tested and this seems to work fine and is the easiest solution outside of changing the environment itself.

You could also try with flattening the observations by modifying the expert trajectory npz file before staging it. However some issues might pop up around keys disappearing (might get an arr_0 () issue etc) because how the npz file is handled. I'm sure if you have existing outputs that you want to extract you can open the npz, flatten the observation key values and save to a new npz. A snippet of how you could do it is below (haven't tested it)

```
def post_processing_flatten(expert_file):
    expert_data = dict(np.load(expert_file))
    print("my keys are:" + str(expert_data.keys()))
    obs = expert_data['obs']
    print(obs.shape) #pre-flatten shape (n,n)
    expert_data['obs'] = obs.flatten()  # convert to 1D array
    print(obs.shape) #post-flatten shape (n,)
    np.savez(expert_file, expert_data)

model = DQN(MlpPolicy, env, verbose=1)
generate_expert_traj(model, 'expert_trajectories', n_timesteps=100, n_episodes=10)
post_processing_flatten('expert_trajectories.npz')

dataset = ExpertDataset(expert_path='expert_trajectories.npz', traj_limitation=10, verbose=1)
model = GAIL('MlpPolicy', env, dataset, verbose=1)
model.learn(total_timesteps=100)
model.save("gail_experiment")
```

Hope this helps!
