### ISSUE TITLE
customenv return from reset does not match the observation space

### ISSUE THREAD

**Issue by RishiKasam** [hill-a/stable-baselines#1162]
Hello, I am pretty new to the field of reinforcement learning. I made a cust env and when I try to use the checkenv from sb3, I am getting an error. I am attaching the pictures of the error shown as well as my function. It would be great if someone can help me with this. Thanks in advance.
<img width="560" alt="ac_func_github" src="https://user-images.githubusercontent.com/64210980/167474737-cee5aa41-8991-4ea2-9105-36ecfbdc46d6.png">

<img width="648" alt="checkenv_error_github" src="https://user-images.githubusercontent.com/64210980/167474477-cd8be8c3-0197-419f-b90b-1566bbd2af4d.png">

**Comment by Miffyli** [comment]
Hey. These issues are for bug reports and enhancements proposals (also, please fill in the template next time). I suggest you print out whatever comes out from reset etc to make sure the results match the observation space. You need to ensure you are returning an array (of size one) instead of a scalar (which has a shape `()`). If you believe there is an error, open up a new issue as a bug report.

Closing as no tech support.
