### ISSUE TITLE
Automatically apply DummyVecEnv on Env for models that require VecEnv [enhancement]

### ISSUE THREAD

**Issue by shwang** [hill-a/stable-baselines#134]
Some models, like PPO1, automatically "unwrap" `VecEnv`s upon initialization rather than throwing an Exception.

By extension, it might make sense to automatically apply the `DummyVecEnv` wrapper to the `env` parameter in models like PPO2 that are incompatible with Envs that don't subclass VecEnv.

**Comment by araffin** [comment]
Hello,
it is done when you pass a string here https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L45 but that needs the environment to be registered.

The idea is use the vec env everywhere (or use the string) to instantiate the environment (in the doc, I think there are only examples with vec env).

Unwrapping only work when `n_env=1`, otherwise, it throws also an error.

I don't think that wrapping automatically VecEnv is a good idea for different reasons:
- we want to have the same api almost everywhere and enforcing that people use VecEnv is a good practice for me
- VecEnv are required when you want to use wrappers like VecNormalize
- we should not hide how multiprocessing is done (and that is also the main reason for having VecEnv)

However, I think that adding a utility function to create a VecEnv would be a good idea (see https://github.com/araffin/rl-baselines-zoo/blob/master/utils/utils.py#L42 for an  example), it is on the roadmap ;)
