### ISSUE TITLE
Example with CnnLstmPolicy

### ISSUE THREAD

**Issue by bbalaji-ucsd** [hill-a/stable-baselines#18]
I tried to run with "Breakout-v0" and got this error.

ValueError: Cannot reshape a tensor with 16384 elements to shape [0,128,?] (0 elements) for 'model_1/Reshape_1' (op: 'Reshape') with input shapes: [32,512], [3] and with input tensors computed as partial shapes: input[1] = [0,128,?].

**Comment by araffin** [comment]
Hello,
can you provide us with minimal code to reproduce the error ?
(here the algorithm is missing)

**Comment by araffin** [comment]
Ok, I see your problem, the default hyperparameter of PPO2 is `nminibatches=4` but as stated in the [docs](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2), for recurrent policies, it should be smaller or equal than number of environments run in parallel.
So, in your example, it will work if you specify `nminibatches=1`.
I think i will add an assert to have a better error message, thanks for reporting it ;)

By the way, you should use the [atari game wrapper](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#id1) to instantiate the algorithm. It will do some important preprocessing on it.
And you should be using the `BreakoutNoFrameskip-v4` instead of `Breakout-v0`.

**Comment by araffin** [comment]
An assert was added in #19, now merged with master

**Comment by bbalaji-ucsd** [comment]
Thanks!
