### ISSUE TITLE
pip: stable-baselines requires tensorflow, breaks preinstalled tensorflow-gpu

### ISSUE THREAD

**Issue by EliasHasle** [hill-a/stable-baselines#193]
I was wondering why my GPU no longer showed up when running tensorflow, and found out I had the package tensorflow installed in addition to tensorflow-gpu. a `pip show tensorflow` revealed that the tensorflow package is required by stable-baselines. I removed tensorflow and tensorflow-gpu, and then installed tensorflow-gpu again, and stable-baselines seems to work with GPU (Algorithm: PPO2, Env: SubprocEnv of a wrapped Retro SuperMarioBros, policy: CnnLnLstmPolicy).

Since breaking preexisting installations is no good, I suggest removing tensorflow as a dependency. Would that break anything, except requiring users to install tensorflow(-gpu) separately?

**Comment by araffin** [comment]
Hello,
I think I've encountered this issue in the past (and @Florence-C too). Surprisingly, this issue does not always happen.
However, I would not remove tensorflow from dependencies (because `pip install stable-baselines` won't work anymore) but rather add an option to download stable-baselines with gpu dependency (ex: `pip install stable-baselines[gpu]`) or maybe detect automatically if tensorflow is already installed or not (and using something like [that](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) to know the version).

**Comment by shirley-wu** [comment]
I encountered this issue too, and I ended up removing tensorflow after installing stable-baselines, and installing tensorflow-gpu again. If you just want a temporary solution, this can work.
However, I don't think it's a proper solution, and I am happy to see this issue solved more beautifully.

**Comment by EliasHasle** [comment]
I am afraid it isn't easy, considering that the genius bunker of Deepmind hasn't solved it:

> Sonnet will work with both the CPU and GPU version of tensorflow, but to allow for that it does not list Tensorflow as a requirement, so you need to install Tensorflow separately if you haven't already done so.

Of course, autodetecting would be a preferred solution, but when that is not available, disabling tensorflow-gpu is far from the second choice for me. Then I prefer "failed to import tensorflow", followed by "Aha! I have to install tensorflow separately!" :-)

**Comment by araffin** [comment]
@EliasHasle can you try with the [fix-tf-install](https://github.com/hill-a/stable-baselines/tree/fix-tf-install) branch?
It should fix most of cases.
