### ISSUE TITLE
Unconsistent Behavior in automatic env creation

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#21]
**Describe the bug**
When creating an env passing a string, using `model.env` for testing won't work for DeepQ, PPO1 and TRPO.

**Code example**
```python
import gym

from stable_baselines import DeepQ
from stable_baselines.common.vec_env import DummyVecEnv

model = DeepQ(policy="MlpPolicy", env='CartPole-v1')

# env = DummyVecEnv([lambda: gym.make('CartPole-v1')])
env = model.env
obs = env.reset()
for _ in range(100):
    action, _ = model.predict(obs)
    obs, reward, done, _ = env.step(action)
```
raises
```
~/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py in step(self, action)
     52 
     53     def step(self, action):
---> 54         assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
     55         state = self.state
     56         x, x_dot, theta, theta_dot = state

AssertionError: array([1]) (<class 'numpy.ndarray'>) invalid

```
because the action is an array instead of an int.
However, replacing `env = model.env` by `env = DummyVecEnv(...)` makes things work.

**System Info**
Describe the characteristic of your environment:
 * Installed via pip or from source

**Comment by araffin** [comment]
@hill-a a simple fix to this problem would be to return always a vec env when using get_env(), no ? (and dissalow the direct access to model.env)
But that may breaks other parts of the code

**Comment by hill-a** [comment]
Good catch, 

I think a better thing to do is for the predict function to detect if the observation is vectorized, and respond accordingly. This should be done with every method, so that predicting non vectorized environment (when validating for example), will work with every method.

This would also mean making sure we are not using a recurrent policy when predicting (they need a vectorized environment).

I'll start tinkering a solution for this.
