### ISSUE TITLE
[Question]  DDPG parameters

### ISSUE THREAD

**Issue by y428lin** [hill-a/stable-baselines#211]
Hi,

I think that we can define the custom policy for the action network for DDPG in stable-baselines. But how could we define the critic network size? Thank you.

Best,
Yuan Lin
University of Waterloo

**Comment by araffin** [comment]
Hello,

In fact, when you define the custom policy for DDPG, both the actor and the critic are changed (see [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ddpg/policies.py#L158)). If you want something more custom, then you will have to define a class that inherits from the DDPGPolicy class.
Corresponding doc (for actor critic models, not DDPG, but this is the same idea): https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html

**Comment by y428lin** [comment]
Thank you for the reply. I have another question about DDPG parameters. In DDPG parameters, there is the default "observation_range=(-5.0, 5.0)". However, I use Gym Environment and already defined the observation space in Gym. Do I still need to change the "observation_range" in DDPG parameters? I use the MlpPolicy for DDPG.

King regards,

**Comment by hill-a** [comment]
Hey,

`observation_range` is used to clip the observation in the DDPG model, by default it is at [-5.0; 5.0] so that a normalized observation (mu, sigma = 1, 1) will almost never be clipped except if the value was unexpectedly large.

To awnser your question, if you have normalized your observations then no you do not need to change  the `observation_range` and the `observation_range` is not using the environment observation space.

I recommend you should normalize either your environment using `stable_baselines.vec_env.VecNormalize` [(link here)](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecnormalize), or that you set the hyperparameter `normalize_observations=True` in [DDPG](https://stable-baselines.readthedocs.io/en/master/modules/ddpg.html#parameters)

Good luck

**Comment by y428lin** [comment]
Hello,

Thank you for information. I would like to ask another question on episode termination for ddpg. For termination, is the y = r + gamma*(1-d)*Q(s') in ddpg in stable baselines, wherein d is the indicator for termination (d=1 when terminated).

King regards,

**Comment by araffin** [comment]
>, wherein d is the indicator for termination (d=1 when terminated).

If the question is `d = done`, then the answer is yes.

The same is done for SAC for instance: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L213
