### ISSUE TITLE
[Question] PPO Actor Crtitc Network

### ISSUE THREAD

**Issue by RGring** [hill-a/stable-baselines#215]
Hey,
I have a few questions, regarding the Networks with PPO1/PPO2. Am I right to assume, that the same network is used for the Critic and Actor?
Furthermore I was wondering how you map the last layer (nature cnn it would be 512-FC) to the discrete or continuous actions (actor) or the expected value (critic). I wasn't able to find the code section.

Thanks for your help and the nice library!
Ronja

**Comment by araffin** [comment]
Hello,

>Am I right to assume, that the same network is used for the Critic and Actor?

By default, in case of images as input (using CnnPolicy), yes. Otherwise, if it is a mlp policy, there are two different networks. But this can be easily changed (cf doc).

>Furthermore I was wondering how you map the last layer (nature cnn it would be 512-FC) to the discrete or continuous actions (actor) or the expected value (critic). I wasn't able to find the code section.

The code section you are looking for is [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L440)
