### ISSUE TITLE
Unable to import stable_baseline

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#239]
When trying to import stable_baseline:

from stable_baselines.common.policies import MlpPolicy, MlpLstmPolicy, MlpLnLstmPolicy

I get:

Exception has occurred: AssertionError
expected file or str, got <_pydevd_bundle.pydevd_io.IORedirector object at 0x000001C4DA4FB2B0>

**Comment by araffin** [comment]
Hello,
please fill the issue template.

**Comment by hn2** [comment]
Update:
After upgrading to the latest version of tensorflow (1.13.1) I get:
Failed to load the native TensorFlow runtime
When trying to import stable_baseline

**Comment by AdamGleave** [comment]
Does `import tensorflow` on its own work OK? It sounds like you have a broken TensorFlow installation, which is not a Stable Baselines issue.

**Comment by hn2** [comment]
Yes that was a tensorflow insulation problem. I fixed that.

However  now I have another problem:

My action space is continuous (-1,1) 

My observation space is 3 dimensional for example (7,3,5)

I get an error message: can not broadcast array of shape (7,3,5) into shape (2).

I am experimenting with ppo1 and will also try ddpg (and possibly other algos with different hyper parameters)

I am trying to implement this env with stable baseline:

http://www-scf.usc.edu/~zhan527/post/cs599/

 

Regards,

Hannan

**Comment by araffin** [comment]
>My observation space is 3 dimensional for example (7,3,5)

A simple solution consists in reshaping your observation to a 1D vector, so you can use MlpPolicy on it.
Otherwise, if you want to keep your observation with that exact shape, then you have to define a custom policy, as the default CnnPolicy was made for images (of shape 64x64xn) and normalization (dividing by 255.) is automatically applied in this [case](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L416).

Again, do not forget to add more context for your problem next time by filling COMPLETELY the issue template ;)

I will close this issue as the topic is different now.

**Comment by hn2** [comment]
Actually I was wrong the error message that I get is :

ValueError: could not broadcast input array from shape (2) into shape (7,3,5)
