### ISSUE TITLE
[question] Reset() in VecEnv

### ISSUE THREAD

**Issue by pulver22** [hill-a/stable-baselines#245]
Hi,

while running my simulations using PPO2 in a VecEnv I noticed a weird behaviour. By design, when the done is set to True in the episode, the reset() method is automatically called and an observation is return.

```    
    def step_wait(self):
        for env_idx in range(self.num_envs):
            obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] =\
                self.envs[env_idx].step(self.actions[env_idx])
            if self.buf_dones[env_idx]:
                obs = self.envs[env_idx].reset()
            self._save_obs(env_idx, obs)
        return (np.copy(self._obs_from_buf()), np.copy(self.buf_rews), np.copy(self.buf_dones),
                self.buf_infos.copy())
```

I am wondering if this makes sense. In my scenario, a robot crashes into an obstacle and, due to the reset() method, the observation returned is not the crash but the one obtained immediately after resetting the position. In this way, the robot shouldn't learn to avoid obstacles because it's not learning to associate a bad reward to the obstacles but to a random position in the environment.

Please correct me if I am wrong.

**Comment by araffin** [comment]
Hello,

>Please correct me if I am wrong.


I think the current implementation is correct. As a reminder, we are in the Markov Decision Process ([MDP](https://en.wikipedia.org/wiki/Markov_decision_process)) framework.

So, given an observation o_t at time t, the agent takes an action a_t. From those two, a reward r_t and termination done_t are computed.
If the episode is not over (`done_t = False`), the agent receives a new observation o_{t+1}, otherwise a new episode begin, and therefore the agent receives the first observation of the next episode (`obs = env.reset()`)

Without VecEnv, the workflow looks like this:

```python
obs  = env.reset()
# Forever
while True:
    # Choose an action given the observation, here a random agent
    action = env.action_space.sample()
    # One step in the env
    obs, reward, done, _ = env.step(obs)
    # If the episode is over, start a new one
   # note that the obs variable is replaced here
    if done:
       obs = env.reset()
```

> In this way, the robot shouldn't learn to avoid obstacles because it's not learning to associate a bad reward to the obstacles but to a random position in the environment.

In your case, what causes the crash is taking a given action in a certain situation, so it is not random. Giving the observation of the crash would not add more information, as it is already contained in both the terminal signal (done) and the reward (I suppose you maybe give a negative reward for crashing).

**Comment by pulver22** [comment]
> Giving the observation of the crash would not add more information, as it is already contained in both the terminal signal (done) and the reward (I suppose you maybe give a negative reward for crashing).

Ok, I guess this makes sense. Thank you for clarify this point!
