### ISSUE TITLE
[Question] Algorithmic differences between stable-baselines and OpenAI Baselines

### ISSUE THREAD

**Issue by Pastafarianist** [hill-a/stable-baselines#276]
When I am conducting experiments and find that some approach works well, I want to compare my results to an established baseline. OpenAI Baselines is one, but (for obvious reasons listed in the readme) I would prefer to use `stable-baselines`. However, to do that, I would like to know what the substantial differences between the two are.

Is there any documentation on the differences in terms of algorithm implementation and performance (as opposed to refactoring or documentation) between `stable-baselines` and OpenAI Baselines?

In my particular case, I am interested in PPO and DQN, but perhaps others could benefit from a precise specification for other algorithms too.

https://github.com/hill-a/stable-baselines/issues/93#issuecomment-441119229 is related but does not answer this question directly.

Note: I do not have rights to assign labels to issues, but this should be a `question`.

**Comment by araffin** [comment]
>However, to do that, I would like to know what the substantial differences between the two are.

The short answer: there should be no differences between OpenAI Baselines and stable baselines.

The longer one: apart from Soft Actor-Critic (which is not part of the original repo), all other algorithms have only been (heavily) refactored, no changes in the algorithm were made (or at least intended). 

However, because we made a lot of changes, they may be some slight differences remaining. I created the [rl zoo](https://github.com/araffin/rl-baselines-zoo) in order to check the performances of the algorithms, and now they seem to be on par with the one of OpenAI Baselines.

Among the differences I see, since we forked the repo:
- we clip the action before returning it in case of continuous actions (this only ensure to remain in the valid domain)
- several bug fixes were made to some algorithms (but that was mostly patches made in the original repo too (see #262 for instance)
