### ISSUE TITLE
Using vectorized (batched) actions, obs, and rewards without using vectorized environments

### ISSUE THREAD

**Issue by skervim** [hill-a/stable-baselines#290]
Is it possible to use vectorized actions, observations and rewards without using vectorized environments? 
I have some simulation code, and want to use a custom gym environment as an interface between the simulation code and the stable-baselines agents. The simulation code expects vectorized (batched) continuous actions (e.g. `shape (2,2)`) and also returns (continuous) observations (e.g. `shape (2,2)`), rewards (e.g. ` shape (2,1)` (and dones (e.g. `shape (2,1)`) as vectors.

The gym-interface would look somewhat like this
```
import simulation

class CustomEnv(gym.Env):
(...)
    def step(self, action):
        obs, rewards, dones = simulation.step()
        return obs, rewards, dones, {}

    def reset(self):
        obs = simulation.reset()
        return obs
(...)
```

Is it possible to convert such a gym-environment to a `DummyVecEnv` or is there some other way, so that I could apply the stable-baselines agents (e.g. PPO2)?

**Comment by araffin** [comment]
Hello,
`DummyVecEnv` and its derivative are mostly wrapper around gym env.

from what I understand you cannot do:

```python
env = DummyVecEnv([lambda: CustomEnv()])
```
because your gym env is already vectorized?

Then, what prevents you from defining it as a `VecEnv` subclass? (see [base class](https://github.com/hill-a/stable-baselines/blob/06934264902ce4e3cdd985a0a36b99cc38c1e39e/stable_baselines/common/vec_env/base_vec_env.py#L30))
You need to implement the required method and it should work ;)

**Comment by skervim** [comment]
Thanks :) your advice worked out!

**Comment by utsavpatel22** [comment]
Hi @skervim , I am also facing the same issue, do you have your code public? It would be great if you can share the code.
