### ISSUE TITLE
Documentation does not mention that legacy logging should be configured

### ISSUE THREAD

**Issue by Pastafarianist** [hill-a/stable-baselines#294]
The very first code example from the docs

```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

should produce a line similar to

```
Logging to /tmp/openai-2019-04-28-01-04-12-724654
```

according to https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/logger.py#L575, but it doesn't. This indicates that legacy logging isn't triggered at all. Indeed, in my larger project, configuring `OPENAI_LOGDIR` and `OPENAI_LOG_FORMAT` does not cause logs to appear.

The motivation for having legacy logging is being able to compare results from `stable-baselines` with the results obtained by upstream (in particular, having `eprewmean`).

Library is installed from git commit `0693426`.

**Comment by araffin** [comment]
Hello,

as you pointed out, you need to call `configure()` in order to have the legacy logging enabled:

```python
from stable_baselines.logger import configure

configure()
```
It seems that no mention of that is made in the documentation... (it is only present in the `run_atari.py` files)

However, if you want to monitor training (to have the mean reward during training for instance), I recommend you to use the `Monitor` wrapper (see an [example](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training) in the doc ;) )
