### ISSUE TITLE
[question] problem with CNNpolicy

### ISSUE THREAD

**Issue by kwk2696** [hill-a/stable-baselines#296]
I'm trying to use CnnPolicy in my model,
my observation space is Box(low = 0, high =3, (15, 15, 1)) 
But arises the error:
Negative dimension size cause by subtracting 4 from 4 for 'deepq/model/action_value/c2/Conv2D'
How do I solve this issue?

Or how can I make custom Cnn network?:

**Comment by araffin** [comment]
Hello,

> How do I solve this issue?
>Or how can I make custom Cnn network?:


the answer is in your question: you need a custom CNN network because your input shape is too small for the default one.

It seems you are using DQN, so I recommend you checking [custom policy doc](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html) and the [dqn custom policy doc](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html#custom-policy-network) too.
You need to pass a different `cnn_extractor`.

The source code: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/deepq/policies.py

**Comment by justinkterry** [comment]
@araffin I don't believe this is an RTFM issue at all. I just ran into this issue myself, and I looked through all the relevant documentation and I can't find anywhere that refers to the required size for the default ones. Can you either update the documentation to reflect this, or tell me what to the limits on the default CNN policy are and I'll make a small PR?

**Comment by araffin** [comment]
> don't believe this is an RTFM issue at all.

The RTFM was for the custom policy part (because he identified the other problem correctly).

> Can you either update the documentation to reflect this, or tell me what to the limits on the default CNN policy are and I'll make a small PR?

Good point, in fact we discussed that a bit in that issue: https://github.com/hill-a/stable-baselines/issues/227#issuecomment-478542396

**Comment by justinkterry** [comment]
I'll make a PR to reflect the minimum 36x36 later. Also, when you refer to "the nature CNN" , you mean the CNN architecture used in the original deepmind DQN paper in nature, right?
