### ISSUE TITLE
how do I implement a different reward function in Stable-Baselines...?

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [hill-a/stable-baselines#299]
Hi, so I'm trying to implement curiosity in a Baselines model, but I need access to the rewards. How should I go about getting the reward, and training the model step by step iteratively in Stable-Baselines? Wanting to use the PPO2 model but any model will do. Thanks.

**Comment by araffin** [comment]
Hello,

> I'm trying to implement curiosity in a Baselines mode

I think @simoninithomas tried to do that with the original baselines (with random distillation network). If you are trying to implement ICM (intrinsic curiosity module) or [similar](https://pathak22.github.io/large-scale-curiosity/), I think you can do it as an env wrapper (because it is independent from the policy from what I remember) so you don't have to change the rl model code.

See in the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#wrappers) and in the code for examples of wrappers.
