### ISSUE TITLE
[Feature Proposal] `load(...)` but only for model parameters

### ISSUE THREAD

**Issue by Miffyli** [hill-a/stable-baselines#312]
**Problem**
Currently `ActorCriticRLModel` implements `load(...)` so that it creates the network/model from zero and then loads stored parameters. This creates hefty amount of overhead, and bit of a memory leak if you are not careful, when you only want to change to different set of model parameters, e.g. when evaluating bunch of stored model.

**Suggestion**
* New function for `ActorCriticRLModel` named `load_parameters(str:filename, ...)` which takes in path to a saved model (from `save(...)`) and only loads the model parameters for the agent. Most of this can be done by re-using code already in `load(...)`, with some re-structuring. 
* Required TF `assign` operations would be created during creation of the graph, after `setup_model`. 

We have been using hacky-ish setup like this for our work with success, and thought it could be useful for others as well.

**Comment by araffin** [comment]
Hello,

I think this is a good feature to have. Especially when you want to deploy your model for instance (where you just need the weights of the policy) . 

I have some additional remarks, questions:

If we implement a `load_parameters` (that takes either a list of numpy arrays or a path to a file) we should also implement a `save_parameters` (save weight to a file) and `get_parameters` (returns list/dict of numpy arrays representing the weights)

As I understand, you were suggesting to still use the same `.pkl` file that contains both parameters and data (e.g.  hyperparams) for loading the parameters? I think in that case have a different format for saving the parameters only (e.g. numpy dict) would make more sense.

>New function for ActorCriticRLModel

I would do that for all models.

>Required TF assign operations would be created during creation of the graph, after setup_model.

Why not when calling the `load_parameters`?

Note that if we change the parameters format to be a dict of numpy arrays instead of a list, this would solve that issue too: https://github.com/hill-a/stable-baselines/issues/113

**Comment by Miffyli** [comment]
> If we implement a load_parameters (that takes either a list of numpy arrays or a path to a file) we should also implement a save_parameters (save weight to a file) and get_parameters (returns list/dict of numpy arrays representing the weights)

Yes I was suggesting using same `.pkl` file that contains both parameters and data/hyperparams. This was for simplicity reasons and to avoid additional file types and such. However looking at some of the algorithms (e.g. DQN, which store replay memory), I can see the reasoning behind having separate functions for `save_parameters` and `get_parameters`.

> I would do that for all models.

Definitely. For some reason I completely missed DQN/HER/etc also have `load`, just defined in algorithm's class.

> Why not when calling the load_parameters?

That works too, but it should check if `load_parameters` has been called before and only then create `assign` operations, otherwise we will keep adding operations to the graph. I originally planned to have all graph creation in roughly same place.

> Note that if we change the parameters format to be a dict of numpy arrays instead of a list, this would solve that issue too: #113

Sounds good, given that we are already tinkering with those functions. We did this in our project as well (we wanted to only load specific layers, and keep some of the randomly initialized). One question though: Should the name be directly the node name in TF? The layer names could change in future, even though the layer stays same (shape and usage). I figure this is the most straight-forward solution, and people could use it to only load specific layers (e.g. only load parameters for nodes that were given in the dict).

**Comment by araffin** [comment]
>DQN, which store replay memory

in fact, that is not the case ^^" (for disk usage reason)

>Yes I was suggesting using same .pkl file that contains both parameters and data/hyperparams. 

The more I think about, the more I don't know what is best (having a "special" file format for parameters or keeping the pickle file), what do you think @hill-a ? @AdamGleave ? @erniejunior ?

>Should the name be directly the node name in TF? 

Good question, I would say yes a priori (need to think more about that). Anyway, we should be backward compatible (allowing to pass a list instead of a dict) and yes maybe allowing to load specific layers/load without looking at the keys can be possible (maybe having a keyword that allows that as in [keras](https://github.com/keras-team/keras/blob/c3eb62763fcc5029c26b025ba1b60d7788d491a1/keras/engine/network.py#L1169)).

One important thing maybe: we should use ordered dict (or python >= 3.6) otherwise some orders problems may occur.

**Comment by hill-a** [comment]
>>If we implement a load_parameters (that takes either a list of numpy arrays or a path to a file) we should also implement a save_parameters (save weight to a file) and get_parameters (returns list/dict of numpy arrays representing the weights)
>
> The more I think about, the more I don't know what is best (having a "special" file format for parameters or keeping the pickle file), what do you think @hill-a ? @AdamGleave ? @erniejunior ?

I dont like pickle personally, it has a lot of flaws. It is used here to keep the saves in one file.

Using [numpy's npz file format](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html) would be nice, as it would be able to store the node name as the key, and the arrays as the values. This would allow some nice tinkering with the parameters, like partial parameter changes, and help with ES methods for example.

**Comment by Miffyli** [comment]
I agree using npzs. They are possibly more efficient as well. 

Other class parameters should still be pickles in my opinion, as they are still convenient for any Pythonic type/class. This will result to two separate files (pkl and npz), where .pkl would refer to desired .npz file (filename of the desired npz file?). For backwards-compatibility, we still would read old lists of params if found. 

If we get some consensus on this I can start working on a pull-request for this.

**Comment by erniejunior** [comment]
:+1: for npz with numpy arrays. Maybe use the compressed version though?
I think we should just use the names of the numpy variables as keys and start documenting how variables are named by our built-in policies. If those names are too confusing, we should rethink our naming scheme.

However, I think the issue we are trying to solve here is trickier than it seems at a first glance. This are the elements we possibly would want to store and restore later:
* Policy Class (the python class)
* Policy Hyper-Parameters <- a dict
* Policy Parameters (NN weights and biases) <- numpy arrays
* Policy State (when it is a recurrent policy) <- numpy arrays
* RL Algorithm Class (the python class)
* RL Algorithm Hyper-Parameters <- a dict
* RL Algorithm State (examples include replay memory, PPO with adaptive KL Penalty Coefficient, Adam ist actually stateful)

The interdependencies between those elements are actually quite complex. E.g. some hyperparameters might be exchanged between different RL Algorithm classes while other are specific to the RL algorithm. Actor-Critic policies can be exchanged between different Actor-Critic Algorithms but are useless with DQN. Some parts of the algorithm state might be transferable to completely different algorithms (like the state of Adam or the replay memory) while others like the adaptive KL penalty coefficient are very specific to a single algorithm.

It might be beyond the scope of this library to handle and warn the application developer about all those interdependencies. It is therefore even more important to clearly document what elements are involved in each of our save/load functions.
I would even go so far and only provide a simple interface to get and set those elements easily and then leave the application developer to decide how to store them. If we decide for a file format upfront we impose a lot of rigidity (e.g. I like to store stuff in databases instead of files and which of the elements to store or not might be very application specific)

**Comment by araffin** [comment]
My idea was more to keep the pickle file in the general case but:
1. save parameters (trained weights) in a dict rather than a list (which is currently the case)
2. allow the use to load/save the parameters only from/in a numpy archive, the use case is you have one pickle file that contains all the hyperparameters for an experiments and several numpy archives for different results of the optimization with the same hyperparams

**Comment by Miffyli** [comment]
To get this to a closure, I'd suggest going back to the original part and implement the following:

* object-function `load_parameters(str_or_List)`:
  * If parameter is a a string, attempts to load parameters from the specified `.pkl` 
  * If List, assumes it contains numpy arrays that are to be loaded as parameters
    * This is to allow modifications to the parameters (e.g. ES)
* object-function `get_parameters` which returns the Tensorflow parameter tensors, _and_ the current parameters as numpy arrays.

`load_parameters` creates and stores necessary Tensorflow operations. Saving of parameters would be done via the current `save`, so we won't have extra file formats for now.

**Comment by araffin** [comment]
Sounds good, but I would accept/return dict first and fallback to list of parameters if needed (as discussed before).
I think that's good for now not to have `save_parameters`, this can be done by the user easily.
