### ISSUE TITLE
Creating a custom policy that combines CNN Policy and MLP Policy

### ISSUE THREAD

**Issue by arunk786** [hill-a/stable-baselines#321]
Hi,

I need a custom policy/architecture which takes two sets of inputs: 1) Images 2) Measurement Vector Data eg. (dist,speed,etc.)
I need to apply CNN for images and MLP for Vector Data and their outputs are concatenated and further processed jointly.

As per the API [https://stable-baselines.readthedocs.io/en/master/modules/base.html](https://stable-baselines.readthedocs.io/en/master/modules/base.html) i can pass only a single policy object. Please let me know the feasible way if any.

**Comment by araffin** [comment]
Hello,
I think your issue is related to the dict space one (see #133 ), for now the best way of doing it is to pretend that your input is a big 1D vector and then split it and resize it (and normalize it if needed) in the custom policy.
So, it is feasible, but it requires some hacks for now, we would really welcome contribution to add support for dict observation.

**Comment by arunk786** [comment]
Thank you @araffin

**Comment by arunk786** [comment]
> Thank you @araffin
