### ISSUE TITLE
[feature request] Go-Explore: a New Approach for Hard-Exploration Problems

### ISSUE THREAD

**Issue by marvin-hansen** [hill-a/stable-baselines#323]
Would you please add the new Go-Explore RL algorithm? 

So far, no reinforcement learning (RL) algo was able to fully, solve the Atari games Montezuma’s Revenge and Pitfall. The new Go-Explore algorithm does just that: On Pitfall, Go-Explore with domain knowledge is the first algorithm with a mean score of almost 60k points exceeding expert human performance.

Because of the high performance at relatively cheap computational costs, the Go-Explore algorithm family might establish new SOTA scores on existing hard problems. Therefore, a reliable base implementation would be most appreciated. 

**Additional context**
GH Repo: https://github.com/uber-research/go-explore
Paper: https://arxiv.org/abs/1901.10995
Blog: https://eng.uber.com/go-explore/

**Comment by araffin** [comment]
Hello,
I would consider go-explore as out of scope of the current project, notably because of its strong assumptions. From what i remember (correct me if i m wrong):
- it requires the environment to be deterministic
- it requires the state of the env to be "savable" so you can restore it later
- it is limited to discrete actions

Those assumptions makes it good for solving atari games like Montezuma, however, i feel quite limited the other type of problem where you can apply it.

**Comment by marvin-hansen** [comment]
I think the authors discussed some of the issues you have mentioned, but I would argue the biggest drawback is actually the codification of domain knowledge* in the overall approach so I guess there is just no way to make that algo assumption-free. It's a pity because the idea to track memory of previous states and go back to them for further exploration makes a lot of sense to me.  

Thank you for taking a closer look. 

* The publication states, the authors could only solve Pitfall after having backed in some domain knowledge specific to the game. While valid to do so, it actually nullifies the algorithm itself.
