### ISSUE TITLE
Which algorithms have GPU versions?

### ISSUE THREAD

**Issue by sheetalsh456** [hill-a/stable-baselines#361]
Hi,

As far as I see in the code, only PPO2 is a GPU version. 
Are there any other algorithms implemented that have a GPU version?

Thanks! :)

**Comment by araffin** [comment]
Hello,

> Are there any other algorithms implemented that have a GPU version?

If you are asking which algo can run on a GPU, then all of them can.

PPO2 is the "GPU optimized" version of PPO1, as mentioned in the documentation,  "for multiprocessing, it uses vectorized environments compared to PPO1 which uses MPI". That's why it is mentioned for PPO only, because there is two versions.

**Comment by sheetalsh456** [comment]
Okay, thank you! :)
