### ISSUE TITLE
[question] How do I get tensorboard to work with multiple vectorized envs (PPO2)?

### ISSUE THREAD

**Issue by DanielPBak** [hill-a/stable-baselines#450]
If I do the following:

```
env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env] * NUM_ENVS)
model = PPO2(CustomPolicy, env=env, n_steps=n_steps, verbose=1, tensorboard_log='./tb_log')
model.learn(total_timesteps=n_steps*2, log_interval=1, tb_log_name=log_name)
```

Some logs are put into` ./tb_log`.

With NUM_ENVS = 1, my tensorboard shows scalars like "advantage", "learning rate".

With NUM ENV > 1, the scalars page is inactive.

Is it possible to get these scalars?

**Comment by Miffyli** [comment]
The tensorboard should include these variables [judging by this part of the code](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L214). You could try providing `full_tensorboard_log=True` when you create the agent, but I do not see how this would help (it will provide individual advantages as well, rather than just the mean).

A sidenote on your code: You want to provide a list of **functions** that return an environment, not a list of already created environments. I.e. 

```env = DymmyVecEnv([lambda: gym.make('CartPole-v1')] * NUM_ENVS)```
