### ISSUE TITLE
Feature: Add step wise update functionality

### ISSUE THREAD

**Issue by bradkyle** [hill-a/stable-baselines#466]
Hi, I'm looking to do a step wise update on the [stable baselines](https://stable-baselines.readthedocs.io/en/master/index.html) PPO2 agent after having trained it i.e. after having run `model.learn(10000)` I would like to update the agent from within a for loop on a step by step basis:

    agent = PPO2()
    env = gym.make('LunarLander-v2')
    while True:
        action = agent.predict(obs)
        observation, reward, done, info = env.step(action)
        agent.update(observation, reward)

This might seem redundant, however it proves useful for fine tuning an agent's weights on real-world tasks.

Is there anything like this being planned?
And if not would something like this be desired?
Any implementation tips?
Thanks

**Comment by Miffyli** [comment]
I can see the usefulness of this type of API, but you run into trouble with generalization across different methods and their different training algorithms really quickly, which is why I assume baselines/stable-baselines does not take that route.  @araffin I figure stuff like this is not planned?

To get something like this you can try to call [`_train_step`](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L247) directly. The [`learn`](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L305) function should provide information you need to accomplish this.

**Comment by araffin** [comment]
>however it proves useful for fine tuning an agent's weights on real-world tasks.

Why can't you call `.learn()` in the real world?

>Is there anything like this being planned?
>I figure stuff like this is not planned?

No, it is not planned.

>To get something like this you can try to call _train_step directly

Yes, calling the train step is the way to go, but you need to be sure of your pre-processing (take a look at the runner code)

> And if not would something like this be desired?

I would advise you not to do only one gradient step per observation. It is better to collect minibatches, that limit the correlation between samples and reduces the variance.

This could be desired only for off-policy methods like SAC, you can find an example [here](https://github.com/araffin/learning-to-drive-in-5-minutes/blob/master/algos/custom_sac.py#L23), but it is quite easy to implement by creating a class that derives from the stable-baselines class.

**Comment by araffin** [comment]
As this feature is not planned and we gave some line of research to make that feature in a custom version, I will close this issue.
