### ISSUE TITLE
Checkpoint frequency in DQN training

### ISSUE THREAD

**Issue by vfleon** [hill-a/stable-baselines#480]
I hope to train DQN for breakout, and I find there are checkpoint_freq and checkpoint_path. Although I set these two parameters and run the code, only the model in the last training is saved. How should I do if I would like to save checkpoint every 100000 trains?

**Comment by araffin** [comment]
Hello,

It seems the checkpoint path is not used anymore in the code... (I will try to update that soon).
Otherwise, if you look at the examples in the documentation, what you are looking for is called a [callback](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training)
