### ISSUE TITLE
Multi output policies

### ISSUE THREAD

**Issue by H-Park** [hill-a/stable-baselines#502]
Example: in pysc2, some actions require positional arguments, such as move commands. 

This might be too environment specific, but is there a want to allow this?

**Comment by Miffyli** [comment]
@araffin 
I understood it that way, yes. I.e. Support for `spaces.Tuple`/`spaces.Dict` but for actions rather than observations, as discussed in #133 . 

The major modification is same for both: Currently everything is more or less bundled up into arrays, which  makes overall processing of things quite a bit tidier. A support for tuple/dict spaces would require storing variable length arrays/tuples somewhere along the line  as well as creating dynamic number of placeholders and whatnot.

_However_, if the next backend is going to be non-graph one (i.e. TF2 eager mode and/or PyTorch), this should be easier to do with those frameworks. I hate to move more and more stuff to "next-backend" project, but this sounds much more reasonable enhancement alongside new backend, rather than implementing it in current graph-version and then translating it to the new backend.

**Comment by Miffyli** [comment]
No specific timeline other than "soon". The first step would be to support TF2.0 via the backwards-compatible API in 1.14 (see #366), but that would be mostly renaming function calls.
