### ISSUE TITLE
[question] How to generate the same action with the same seed? 

### ISSUE THREAD

**Issue by yutingsz** [hill-a/stable-baselines#539]
Hi Team, 
As an experiment, I try to control the randomness of the action within the learning phase. I set the seed in multiple places. My code is below: 
```python

# Custom MLP policy of three layers of size 128 each
class CustomPolicy(FeedForwardPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomPolicy, self).__init__(*args, **kwargs,
                                           net_arch=[dict(pi=[128, 128], vf=[128, 128])],
                                           feature_extraction="mlp")

n_cpu = 1
seed = 1
nv_id = 'CartPole-v1'
env = DummyVecEnv([make_env(env_id, 0) for i in range(n_cpu)])

set_global_seeds(seed)
model = PPO2(CustomPolicy, env, verbose=1)
model.learn(total_timesteps=25000, seed=seed)

```
I notice that in the function step, the value action still has different output everytime I restart the line "model.learn". Is there any way to force the the action has the same value when the function runs. 

```python
    def step(self, obs, state=None, mask=None, deterministic=False):
        if deterministic:
            action, value, neglogp = self.sess.run([self.deterministic_action, self.value_flat, self.neglogp],
                                                   {self.obs_ph: obs})
        else:
            action, value, neglogp = self.sess.run([self.action, self.value_flat, self.neglogp],
                                                   {self.obs_ph: obs})
        return action, value, self.initial_state, neglogp
```

**System Info**
The code runs with tensorflow 1.12.0 on the windows CPU

**Comment by Miffyli** [comment]
To summarize: You wish to pick deterministic actions while training (and assuming rest of the randomness is same, pick same actions each time you run the code)? 

This is not supported in the PPO2 by default, but you could take a copy of Runner and [modify the line that creates the action](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L468) to pick deterministic actions rather than stochastic actions.

Note that this can be a bad idea for learning: The agent could easily get stuck in bad actions and never explores other options, and also does not quite fit in with the theory behind PPO2 (the definition expects actions sampled according to policy, not deterministic actions, although PPO's policy clipping might help fixing this).

**Comment by araffin** [comment]
Hello,
i think he just want to have reproducible results, please read the doc for that, there is a seed parameter.

**Comment by yutingsz** [comment]
Hi araffin and Miffyli, 
Thanks for your reply. araffin is correct. I just want to have reproducible results, not deterministic result. In my code above, I already set the parameter seed 
```python 
model.learn(total_timesteps=25000, seed=seed)
```
However when I compare the results from the multiple runs, the results are different. I am using the stable-baseline 2.8.0. I notice the new version, 2.9.0, introduces a new parameter "n_cpu_tf_sess". The document states that it is important to get reproducible results. In the old version, 2.8.0, this parameter is not available. Is it the place to cause the difference?

**Comment by araffin** [comment]
You need to use the master version for that, or wait for the 2.9 release. The seed parameter was also moved to the constructor.

**Comment by yutingsz** [comment]
Thanks @araffin. I modified a part of the 2.8 code on my laptop and manage to generate the reproducible result. One observation is that there are multiple places to set seeds: 1. at the TF graph level, 2. in the Env wrapper, and 3. in the action_space of the Env. I have to define the seeds at all 3 places to get the reproducible results.
