### ISSUE TITLE
[question] Feeding expert knowledge about the actions

### ISSUE THREAD

**Issue by matthew-hsr** [hill-a/stable-baselines#626]
I am aware of the functionality [`.pretrain()`](https://stable-baselines.readthedocs.io/en/master/guide/pretrain.html) which takes in trajectories. But is there anyway we can feed in expert knowledge about the possible actions? (e.g. effect of action 1 is more similar to action 2, but more different from action 3 and 4, etc)

If this functionality is not available, are you aware of any research on this topic and does it speed up training? I'd appreciate if someone can point me to some papers / keywords that I can further look into.

Thanks in advance!

**Comment by araffin** [comment]
Hello,

>But is there anyway we can feed in expert knowledge about the possible actions? 

There is no obvious way of doing so. This will be handled automatically by the agent (if the policy is stochastic, the agent may assign the same probability to both actions, or just choose one of the two (because there are similar)).

> are you aware of any research on this topic and does it speed up training?

What you are looking for is using domain/task knowledge to accelerate training. You have different way of doing so, and one is how you design your observation/action space. This is an open question and I would say it is problem specific.
For instance, in your case, if the two actions are similar, you can choose to remove one.

**Comment by matthew-hsr** [comment]
Thanks!
