### ISSUE TITLE
[feature request] Extend option for ExperienceReplay

### ISSUE THREAD

**Issue by Solliet** [hill-a/stable-baselines#682]
I am using the parts of the repository such as the ReplayBuffer for my own algorithms and research. A common pattern is that of running Batch/Vec environments. The consequence is that the batches need to be separated before they enter the ReplayBuffer. Thus I propose an 'extend' function that behaves like `list.extend` and fills in the buffer with the content of a batch. This will result in something along these lines:
```Python
buffer = ExperienceBuffer(2**20)
state = env.reset() #obs now has NxM(xZ) shape
action = agent(state)
nstate, reward, done, _ = env.step(action)
buffer.extend(state, action, reward, nstate, done)
```

I would go about implementing this by considering the shape of done to infer the number of individual observations, then either reusing the `add` method or adding the code to avoid the extra calls.

**Comment by Miffyli** [comment]
Just to recap I understood correctly: Here `state`, `action` etc are lists of states/actions/etc, and with `buffer.extend` we add all of these experiences to the buffer with one call, rather than looping over and doing `buffer.add?`

Sounds like an useful function, and given that Python lists already use this term `extend` for same purpose it should be clean and easy to understand too :). If this is describes the feature you wanted to add, feel free to start working on a PR!

**Comment by Solliet** [comment]
Yes this is what I would like to do. It saves a few lines of code that probably exist on everybody's projects and saves a quite a few functioncalls.
