### ISSUE TITLE
Save model as .h5 file

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [hill-a/stable-baselines#699]
Hello, may I know is there any possible way to save the model as .h5 format instead of .pkl after the training?

**Comment by Miffyli** [comment]
There is no pre-made function for this. However, since stable-baselines v2.8.0 the models are saved in a .zip format, [detailed here](https://stable-baselines.readthedocs.io/en/master/guide/save_format.html), which you can load yourself with `zipfile` and `numpy` libraries without dependency on stable-baselines with something like (pseudo-code, haven't checked for validity):

```python
import zipfile
import io
import numpy as np

model_file = zipfile.ZipFile(path_to_model, "r")
parameter_bytes = model_file.read("parameters")
parameter_buffer = io.BytesIO(parameter_bytes)
parameters = np.load(parameter_buffer)
```

**Comment by ChunJyeBehBeh** [comment]
then how can I save it into .h5? It would help also if it can be saved into json file

**Comment by Miffyli** [comment]
Quick googling gives this: http://docs.h5py.org/en/latest/quick.html ... 

Note that "parameters" only contains model parameters. "data" contains the class parameters (e.g. training parameters) in a JSON format.

**Comment by QuXinghuaNTU** [comment]
> then how can I save it into .h5? It would help also if it can be saved into json file

Hi, 

Did you figure out how to convert and save the model into .h5 file?
