### ISSUE TITLE
PPO2 training very unstable for complex environement

### ISSUE THREAD

**Issue by nono9212** [hill-a/stable-baselines#768]
Hi,

I have been struggling to get PPO2 to work on the custom environement made by unsupervised.ai for their robot to learn to walk. But despite a ton of simulations and tweaking of the reward function, I can't get the robot to walk.
I found that because of the scaling of my reward function, I should better let cliprange_vf set to -1. 
I then adapted the optuna optimization algorythme to find the best hyperparameters, but I realized that the performance were really unstable during training. Plus, once it knows how not to fall, it doesn't seem to improve its reward by starting to go towards its objective...

I you have any idea on how to make it work I would be pleased to hear it. Or maybe PPO2 is not well suited for this environment... I don't know, I'm very new to this field.

You can checkout the code at [https://github.com/nono9212/aida_gym](https://github.com/nono9212/aida_gym)

![image](https://user-images.githubusercontent.com/6367093/77582556-dfd10000-6edf-11ea-990f-561a7a33bc21.png)

**Comment by Miffyli** [comment]
These issues are not generally for tech support, so we can not give lengthy advice, but would @araffin have any suggestions for such robotics envs?

**Comment by araffin** [comment]
Hello,
I tried to use the environment but there is a ton of warnings because inertial data is missing from the urdf (which is not a good sign).
Then, I would recommend you to use the rl zoo (you just need to register your env as it is described in the doc), look at hyperparameters for BulletEnv and try SAC or TD3 that are more appropriated for continuous control.
Also, you should use deterministic evaluation (cf doc, it done in the zoo).

Closing this issue as "r/reinforcementlearning/" or stack overflow would be a more appropriate place.
