### ISSUE TITLE
Tensorflow requirement not satisfied but installation succeeds

### ISSUE THREAD

**Issue by mhtb32** [hill-a/stable-baselines#849]
I tried installing stable-baselines in a virtualenv in python 3.7.7 and Ubuntu 18.04:
```bash
pip install stable-baselines
```
Although there is no version of TensorFlow installed in that environment, the setup doesn't collect and install it and proceeds with:
```bash
Successfully installed stable-baselines-2.10.0
```
How is that?

**Comment by araffin** [comment]
>How is that?

That's an issue of pip and tensorflow in fact...
If you want the correct tensorflow to be installed at the same time, use `pip install git+https://github.com/hill-a/stable-baselines` (it will install the version from master and handle tensorflow dependency properly).

Because tensorflow could not handle properly cpu vs gpu installation, we had to put a condition in the `setup.py`. However, after packaging stable-baselines into a pip package, this condition is no longer checked... As a result, you need either to install from source (`pip install git+https://github.com/hill-a/stable-baselines`) or install the correct tensorflow version manually.
