### ISSUE TITLE
[question] Import external parameters into the agent policy network

### ISSUE THREAD

**Issue by FabioPINO** [hill-a/stable-baselines#859]
I want to import external nn parameters from a personal pre-trained  tensorflow based neural network(nn) into the policy of my Stable Baseline(SB) agent. I have been looking at the SB saving methods but they do not look very clear to me.

**Comment by Miffyli** [comment]
The answer is in documentation: [`agent.load_parameters(parameters_as_dict)`](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.load_parameters).

**Comment by FabioPINO** [comment]
Thank you for your prompt reply! Do I have to import my parameters in .npy?

**Comment by Miffyli** [comment]
You can load the parameters into a dictionary, where keys are parameter names (where to assign the values) and values are the numpy arrays containing those values, see [`get_parameter_list()`](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.get_parameter_list) for getting those parameters.

Sidenote: Should probably write a simple example of this somewhere, too.

You can close this issue if that answers your question.

**Comment by FabioPINO** [comment]
Thank you! I'll have a go!

**Comment by FabioPINO** [comment]
@Miffyli  I finally managed to import a pre_trained policy into my PPO2 agent. Although, there are some issues I'd like discuss with you.

1. I tried two different configurations: shared NN between policy and value and separated NN. In both cases the results of the RL are not as good as expected. It seems that even imposing a correct pre trained policy the fact that no assumptions are made on the value function damage the training.

2. I still have some problem to understand correctly how the algorithm select an action. Reading some papers and documents, I've understood that the action is drawn from a pdf parametrized with mean and sdv, but I am still struggling to figure out the link between this and the policy network.

3. I noticed it is possible to enable an option for deterministic policy in PPO2, how does it work precisely.

**Comment by Miffyli** [comment]
1) Sounds indeed possible, since the pre-trained weights were trained for good policy. Reading through papers, people seem to use pre-trained weights by minimizing the KL distance to this policy rather than using weights as starting point. See e.g. [this paper](https://arxiv.org/abs/2003.06066) and [the OpenAI rubik's cube paper](https://arxiv.org/abs/1910.07113).

2) Network turns observation into the mu and std, which define the normal distribution and from which we sample the action.

3) This means you will always get the same action for same input. E.g. in case of continuous actions this returns the mu as an action. 

Unfortunately I can not give more advice here, as this ventures to somewhat uncharted territory. The whole RL +imitation learning stuff is still very ongoing research.

**Comment by araffin** [comment]
Closing this as the original question was answered.
