### ISSUE TITLE
Network architecture keyword argument consistency

### ISSUE THREAD

**Issue by cisprague** [hill-a/stable-baselines#948]
This is a minor issue but was a bit confusing when first encountered. Should be an easy fix.

In `common.policies.MlpPolicy` the network-architecture keyword argument is `net_arch`, whereas it is `layers` in `sac.MlpPolicy`.

**Comment by araffin** [comment]
Hello,

This is in fact an inconsistency that is fixed in SB3. The original reason for it was that `sac.MlpPolicy` is quite different from the common policies (you cannot pass `dict(vf=[], pi=[])` but only a list).
I would appreciate a PR that solves that issue ;) (but that keep backward compatibility)

**Comment by araffin** [comment]
Fixed in SB3: https://github.com/DLR-RM/stable-baselines3
